server:
  port: 8801

spring:
  data:
    redis:
      host: xxx.xx.xx.xxx
      port: 6379

  datasource:
    url: jdbc:mysql://xxx.xx.xx.xxx:3306/alua
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    protocol: smtp
    port: 465
    host: smtp.gamil.com
    username: example@gmail.com
    password: password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
